#!/bin/bash -e

#©keithhedger Fri 11 Nov 11:13:52 GMT 2016 kdhedger68713@gmail.com


FILENAMES=( "text-x-gettext-translation.png" "application-x-shellscript.png" "text-x-c++src.png" "text-x-makefile.png" "text-x-patch.png" "application-x-python.png"  "text-x-python.png")

cd "$1"
INDEX=0
while [ $INDEX -lt ${#FILENAMES[@]} ]
	do
		while read
			do
				FOLDER=$(dirname "$REPLY")
				(
					cd "$FOLDER"
					echo "In $FOLDER ..."
					if [ ! -e ${FILENAMES[$INDEX]} ];then
						BASE=$(basename "$REPLY")
						ln -sv "$BASE" "${FILENAMES[$INDEX]}"||true
					fi
					if [ ! -e "inode-x-empty.png" ];then
						if [ -e "empty.png" ];then
							ln -sv "empty.png" "inode-x-empty.png"||true
						else
							ln -sv "text-x-generic.png" "inode-x-empty.png"||true
						fi
					fi
				)
			done < <(find -iname "*${FILENAMES[$INDEX]}")
		((INDEX+=1))
	done
exit 0

FILENAMES=( "empty.png" "shellscript.png" )
LINKNAME=( "inode-x-empty.png" "text-x-shellscript.png" )
cd "$1"
INDEX=0
while [ $INDEX -lt ${#FILENAMES[@]} ]
	do
		while read
			do
				FOLDER=$(dirname "$REPLY")
				(
					cd "$FOLDER"
					echo "In $FOLDER ..."
					if [ ! -e ${LINKNAME[$INDEX]} ] && [ -e ${FILENAMES[$INDEX]} ];then
						BASE=$(basename "$REPLY")
						ln -sv "$BASE" "${LINKNAME[$INDEX]}"||true
					else
						BASE=$(basename "$REPLY")
						ln -sv "$BASE" "text-x-generic.png"||true
					fi
				)
			done < <(find -iname "${FILENAMES[$INDEX]}")
		((INDEX+=1))
	done

FILENAMES=( "text-x-gettext-translation.png" "application-x-shellscript.png" "text-x-c++src.png" "text-x-makefile.png" )

cd "$1"
INDEX=0
while [ $INDEX -lt ${#FILENAMES[@]} ]
	do
		while read
			do
				FOLDER=$(dirname "$REPLY")
				(
					cd "$FOLDER"
					echo "In $FOLDER ..."
					if [ ! -e ${FILENAMES[$INDEX]} ];then
						BASE=$(basename "$REPLY")
						ln -sv "$BASE" "${FILENAMES[$INDEX]}"||true
					fi
				)
			done < <(find -iname "*${FILENAMES[$INDEX]}")
		((INDEX+=1))
	done

exit 0
FROMFILENAMES=( "*text-x-gettext-translation.png" "*application-x-shellscript.png" "*text-x-c++src.png" "*text-x-makefile.png" )
TOFILENAMES=( "text-x-gettext-translation.png" "application-x-shellscript.png" "text-x-c++src.png" "text-x-makefile.png" )

cd "$1"
INDEX=0
while [ $INDEX -lt ${#FROMFILENAMES[@]} ]
	do
		while read
			do
				FOLDER=$(dirname "$REPLY")
				(
					cd "$FOLDER"
					echo "In $FOLDER ..."
					if [ ! -e ${TOFILENAMES[$INDEX]} ];then
						BASE=$(basename "$REPLY")
						echo "ln -sv "$BASE" "${TOFILENAMES[$INDEX]}"||true"
					fi
				)
			done < <(find -iname "${FROMFILENAMES[$INDEX]}")
		((INDEX+=1))
	done
