.\" kkfilemanager
.TH "kkfilemanager" "1" "0.0.0" "K.D.Hedger" "User Commands"
.SH "NAME"
kkfilemanager \- manual page for kkfilemanager 0.0.0
.SH "SYNOPSIS"
.B kkfilemanager
.SH "DESCRIPTION"
A GUI programme.


.SH "EXAMPLES"
.LP 
	does somithing
.IP 
kkfilemanager
.LP 

.SH "REPORTING BUGS"
Report bugs to kdhedger@yahoo.co.uk
